In [2]:
!pip install seaborn

   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   --------------- ------------------------ 112.6/294.9 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 294.9/294.9 kB 3.6 MB/s eta 0:00:00


In [27]:
!pip install opencv-python
import cv2

In [28]:
from matplotlib import pyplot as plt

def cv2_imshow(image):
    # Convert image from BGR to RGB format
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
tf.__version__

'2.15.0'

In [48]:
#path = 'C:\\Users\\malav\\OneDrive\\Desktop\\bigm\\test'

In [49]:
training_generator = ImageDataGenerator(rescale=1./255,
                                        rotation_range=7,
                                        horizontal_flip=True,
                                        zoom_range=0.2)

In [50]:
train_dataset = training_generator.flow_from_directory('C:\\Users\\malav\\OneDrive\\Desktop\\bigm\\train',
                                                        target_size = (64, 64),
                                                        batch_size = 8,
                                                        class_mode = 'categorical',
                                                       shuffle = True)

Found 329 images belonging to 2 classes.


In [33]:
train_dataset.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [51]:
test_generator = ImageDataGenerator(rescale=1./255)
test_dataset = test_generator.flow_from_directory('C:\\Users\\malav\\OneDrive\\Desktop\\bigm\\test',
                                                     target_size = (64, 64),
                                                     batch_size = 1,
                                                     class_mode = 'categorical',
                                                     shuffle = False)

Found 68 images belonging to 2 classes.


In [52]:
network=Sequential()
network.add(Conv2D(32,(3,3),activation='relu',input_shape=(64,64,3)))
network.add(MaxPooling2D(pool_size=(2,2)))

network.add(Conv2D(32,(3,3),activation='relu'))
network.add(MaxPooling2D(pool_size=(2,2)))

network.add(Conv2D(32,(3,3),activation='relu'))
network.add(MaxPooling2D(pool_size=(2,2)))

network.add(Flatten())

network.add(Dense(units=577,activation='relu'))
network.add(Dense(units=577,activation='relu'))
network.add(Dense(units=2,activation='softmax'))

In [53]:
network.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 62, 62, 32)        896       
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 31, 31, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_7 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 max_pooling2d_7 (MaxPoolin  (None, 14, 14, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_8 (Conv2D)           (None, 12, 12, 32)        9248      
                                                                 
 max_pooling2d_8 (MaxPoolin  (None, 6, 6, 32)         

In [55]:
network.compile(optimizer='Adam', loss='categorical_crossentropy', metrics = ['accuracy'])

In [58]:
history = network.fit_generator(train_dataset, epochs=40)

Epoch 1/40
 1/42 [..............................] - ETA: 2s - loss: 0.1423 - accuracy: 1.0000

C:\Users\malav\AppData\Local\Temp\ipykernel_8808\2852573655.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = network.fit_generator(train_dataset, epochs=40)


42/42 [==============================] - 2s 46ms/step - loss: 0.3041 - accuracy: 0.8906
Epoch 2/40
42/42 [==============================] - 2s 47ms/step - loss: 0.2410 - accuracy: 0.9058
Epoch 3/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1789 - accuracy: 0.9271
Epoch 4/40
42/42 [==============================] - 2s 46ms/step - loss: 0.2165 - accuracy: 0.9210
Epoch 5/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1362 - accuracy: 0.9422
Epoch 6/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1874 - accuracy: 0.9392
Epoch 7/40
42/42 [==============================] - 2s 47ms/step - loss: 0.1303 - accuracy: 0.9453
Epoch 8/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1037 - accuracy: 0.9574
Epoch 9/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1190 - accuracy: 0.9453
Epoch 10/40
42/42 [==============================] - 2s 46ms/step - loss: 0.1247 - accuracy: 0.9514
Epoch 11/40
42/42 [=

In [59]:
test_dataset.class_indices

{'mamootty': 0, 'mohanlal': 1}

In [60]:
predictions = network.predict(test_dataset)
predictions

68/68 [==============================] - 1s 7ms/step


array([[9.99989867e-01, 1.01547348e-05],
       [9.99940634e-01, 5.94082521e-05],
       [9.93621171e-01, 6.37888117e-03],
       [9.99997973e-01, 2.04617777e-06],
       [9.99999762e-01, 2.24156594e-07],
       [1.00000000e+00, 1.50321089e-09],
       [9.99607623e-01, 3.92367248e-04],
       [9.99999523e-01, 4.32519954e-07],
       [9.99984026e-01, 1.59679294e-05],
       [9.93943512e-01, 6.05649734e-03],
       [1.00000000e+00, 3.13864419e-08],
       [1.00000000e+00, 3.53752383e-09],
       [9.99404192e-01, 5.95844176e-04],
       [2.80366139e-03, 9.97196317e-01],
       [3.03842016e-02, 9.69615817e-01],
       [1.00000000e+00, 1.23893795e-11],
       [6.03340976e-02, 9.39665914e-01],
       [1.29303098e-01, 8.70696902e-01],
       [2.98941154e-02, 9.70105827e-01],
       [9.62222338e-01, 3.77777070e-02],
       [9.99997139e-01, 2.81466555e-06],
       [9.99958396e-01, 4.15712457e-05],
       [9.99104321e-01, 8.95604433e-04],
       [9.99313951e-01, 6.86026237e-04],
       [9.984616

In [61]:
predictions = np.argmax(predictions, axis = 1)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [44]:
test_dataset.classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(test_dataset.classes, predictions)

0.8088235294117647

In [63]:
from sklearn.metrics import classification_report
print(classification_report(test_dataset.classes, predictions))

              precision    recall  f1-score   support

           0       1.00      0.65      0.79        37
           1       0.70      1.00      0.83        31

    accuracy                           0.81        68
   macro avg       0.85      0.82      0.81        68
weighted avg       0.87      0.81      0.81        68

